[package]
name = "lux-camp-badge-animations"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = { version="0.8", default-features = false, features = ["small_rng"] }
smart-leds = "0.3"
smart-leds-trait = "0.2"
glm = "0.2.3"

lux-camp-badge = { path = "../lux-camp-badge" }